### ISSUE TITLE
Decide how to handle avatars and game covers

### ISSUE THREAD

**Issue by connorshea** [connorshea/ContinueFromCheckpoint#16]
Let's go with ActiveStorage.

- Does it work on Heroku? Yes
- ~~Should we use Carrierwave along with it?~~ No need, ActiveStorage pretty much handles everything that carrierwave would.
- Any other considerations to make?
  - Will need to figure out how to handle upload storage in production, S3 or Google Cloud probably ;-;

- https://guides.rubyonrails.org/v5.2/active_storage_overview.html
- https://blog.heroku.com/rails-active-storage
- https://evilmartians.com/chronicles/rails-5-2-active-storage-and-beyond
- Keep Rails 6 in mind: https://github.com/rails/rails/blob/v6.0.0.beta1/activestorage/CHANGELOG.md

**Comment by AnthonySuper** [comment]
It works on Heroku.

Don't use Carrierwave.

Modify the controller code to stream responses.
